### ISSUE TITLE
Create a new Movie 

### ISSUE THREAD

**Issue by angelo-v** [HydraCG/api-examples#3]
As an administrator of the "Hydra Movies API" I want to be able to add a Movie so that the API is able to serve it to interested clients.

**Comment by tpluscode** [comment]
How would you imagine this to play out from end user's perspective. A form presented directly from the entrypoint page?

**Comment by angelo-v** [comment]
The end user experience depends heavily on the app that is using the API. It could be a classical web frontend that presents a form, as well as a digital assistant with a voice UI. And web frontends could differ and decide to place a form on the start page, hide it in a submenu or lead to the creation process via some sort of flow.

**Comment by alien-mcl** [comment]
Does the administrator want to fully describe the movie being added or to hook up some existing representation (or both)?

**Comment by tpluscode** [comment]
Let's think is baby steps. If we're building a completely new API, then it's simpler to assume we have nothing and those will be completely new movies.

It will be interesting indeed to play with actual API/implementations of the latter. We've drafted that in cookbook but it's yet to be proven a good design :)

**Comment by angelo-v** [comment]
Yes, new movies and all data has to be provided. I only implemented `name` for now, but let's add some more (primitive) data. Proposals?

**Comment by tpluscode** [comment]
In fact, we will quickly run into non-trivial cases with those properties, which may not be supported out-of-the box using existing hydra terms.

For now, the best I can think of would be

1. Replace `name` with `title`
1. Add:
   * [duration](https://schema.org/duration)
   * release Date
   * plot Summary

Try adding anything else and we'll likely encounter more complex graphs or missing features. Either will be tackled separately

**Comment by angelo-v** [comment]
> Replace name with title

What title? schema:title is a job title!

**Comment by tpluscode** [comment]
In general movies have titles not names 😉 

Doesn't have to be schema. 🤷‍♂

**Comment by angelo-v** [comment]
In english you may call it title, but semantically it is still a `schema:name`. That's what the examples use as well.

**Comment by tpluscode** [comment]
Ok, so be it

**Comment by alien-mcl** [comment]
I think @angelo-v had in mind movies properties to be filled in. Any data structure can have any properites and I'm not sure how hydra should support them "out of box". I think its up to the client on how to i.e. generate a form for each property, but my experience shows hydra has nothing to do with this. BTW, I think there is adedicated vocab for movies (iMDb related). Also DC terms would fit nicely

**Comment by tpluscode** [comment]
> I'm not sure how hydra should support them "out of box"

A few examples:

1. One of a set of choices. Example: `gender`
1. One of a set of open choices. Think a dynamically generated `select`. Example: `film genre`
   * a variant of above, where the choices are filtered. Presented as a dynamic combo/autocomplete field 
1. Cardinalities
1. Distinguishing between "new" and "existing" resources

There is probably many more. None of the above we can currently describe, and no, you cannot simply defer this to the client. A really practical API should provide some more information to make an independent client possible.

> but my experience shows hydra has nothing to do with this

Don't get me wrong but apparently your experience is currently limited. There are many practical use cases which we may want to cater for out of the box, or at least suggest non-standard solutions so that real-world applications are possible and Hydra becomes really practical.

This is precisely why we should build these example apis. To gain that experience really building stuff.

> BTW, I think there is adedicated vocab for movies (iMDb related). Also DC terms would fit nicely

I was also thinking about imdb. IMO it doesn't matter which vocabulary we use for domain-specific terms. Could be all minted locally if that made the design process a bit easier for us. It is also the choice Markus made in the original issue tracker.

**Comment by tpluscode** [comment]
On a note related to imdb, I think you could also add a `rdf:seeAlso` property for providing an IMDB link.

**Comment by angelo-v** [comment]
I added two more (simple) properties `duration` and `description` to have a bit more than just the `name`. Let's support `seeAlso` in a different issue.

**Comment by alien-mcl** [comment]
> This is precisely why we should build these example apis. To gain that experience really building stuff.

I've got confused. These are `baby steps`. You suggested working with something simpler like a link rather than with a collection, but now you'd like to throw as much of the data structure description as possible.
We can add new issues addressing these - let's focus on adding a new movie, without getting into details whether the movie has a name or a title or whether the duration can be negative on infinite.

**Comment by tpluscode** [comment]
> but now you'd like to throw as much of the data structure description as possible.

Where did I ever say that?

> let's focus on adding a new movie, without getting into details whether the movie has a name or a title or whether the duration can be negative on infinite.

What good is a movie if it doesn't have some attributes? And what are those attributes if a client does not have enough information to set their values?

**Comment by angelo-v** [comment]
Let's close this, and tackle any missing details in separate issues.
